version: 2

models:
  - name: cc_sales_products
    columns:
      ### PK ###
      - name: qty_91
        tests:
          - not_null
      - name: avg_daily_qty_91
        tests:
          - not_null        